services:
  app:
    build: ./app
    environment:
      - KEY_PATH=/app/secrets/id_ecdsa
    volumes:
      - ${KEY_PATH}:/app/secrets/id_ecdsa:ro
      - //var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./overwatch-dashboard
    ports:
      - "80:80"
    depends_on:
      - app